/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package firstgui;

import javax.swing.JOptionPane;

/**
 *
 * @author jhedding
 */
public class fToCConverter extends javax.swing.JFrame {

    /**
     * Creates new form fToCConverter
     */
    public fToCConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFtemp = new javax.swing.JLabel();
        txtTempInput = new javax.swing.JTextField();
        lblTempCel = new javax.swing.JLabel();
        btnConvertF = new javax.swing.JButton();
        lblNewTemp = new javax.swing.JLabel();
        lblTempFah = new javax.swing.JLabel();
        lblNewTempF = new javax.swing.JLabel();
        btnConvertC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFtemp.setText("Temperature:");

        lblTempCel.setText("Temp in Celcius:");

        btnConvertF.setText("Convert to Fahrenheit");
        btnConvertF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertFActionPerformed(evt);
            }
        });

        lblNewTemp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewTemp.setText("CTemp");

        lblTempFah.setText("Temp in Fahrenheit:");

        lblNewTempF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewTempF.setText("FTemp");

        btnConvertC.setText("Convert to Celsius");
        btnConvertC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lblTempCel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lblFtemp)
                        .addGap(18, 18, 18)
                        .addComponent(txtTempInput, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNewTemp)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTempFah)
                                .addGap(46, 46, 46)
                                .addComponent(lblNewTempF))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnConvertF)
                        .addGap(33, 33, 33)
                        .addComponent(btnConvertC)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFtemp)
                    .addComponent(txtTempInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConvertF)
                    .addComponent(btnConvertC))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewTemp)
                    .addComponent(lblTempCel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewTempF)
                    .addComponent(lblTempFah))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertFActionPerformed
        
        TempFormatStrategy tf = new StandardTempFormat();
        TempConverterStrategy fToC = new FahrenheitToCelciusConverter();
        Double tempF;
        
        try {
            tempF = fToC.convertTemp(txtTempInput.getText());
            lblNewTemp.setText(tf.formatTemp(tempF));
            lblNewTempF.setText(tf.formatTemp(Double.parseDouble(txtTempInput.getText())));
        } catch (IllegalTempException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_btnConvertFActionPerformed

    private void btnConvertCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertCActionPerformed
        
        TempFormatStrategy tf = new StandardTempFormat();
        TempConverterStrategy cToF = new CelciusToFahrenheitConverter();
        Double tempC;
        
        try {
            tempC = cToF.convertTemp(txtTempInput.getText());
            lblNewTemp.setText(tf.formatTemp(Double.parseDouble(txtTempInput.getText())));
            lblNewTempF.setText(tf.formatTemp(tempC));
        } catch (IllegalTempException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_btnConvertCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fToCConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fToCConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fToCConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fToCConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fToCConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertC;
    private javax.swing.JButton btnConvertF;
    private javax.swing.JLabel lblFtemp;
    private javax.swing.JLabel lblNewTemp;
    private javax.swing.JLabel lblNewTempF;
    private javax.swing.JLabel lblTempCel;
    private javax.swing.JLabel lblTempFah;
    private javax.swing.JTextField txtTempInput;
    // End of variables declaration//GEN-END:variables
}
